; ===============================
; oaktree
; Waterbear framework for SNES
; (c) 2015 oaktree Novelties
;
; FILE: system.inc
; DESCRIPTION: System includes
; ===============================
.IFNDEF SYSTEM_H
.DEFINE SYSTEM_H

.define		System_INTERRUPTS_PORT		$4200

.define		System_REGISTER_BYTE		0
.define		System_REGISTER_WORD		1

.define		System_INDEX_SIZE			$10
.define		System_ACCUMULATOR_SIZE		$20

.ENDIF
